/**:
  ros__parameters:
    base_frame: base_link
    use_imu: true
    use_3d_distortion_correction: false
    distance_ratio: 1.03
    object_length_threshold: 0.05
    processing_time_threshold_sec: 0.01
    timestamp_mismatch_fraction_threshold: 0.01
    enable_ring_outlier_filter: true
    max_input_point_count: 691200  # Hesai OT128, dual return, high resolution mode
    max_twist_frequency_hz: 200.0
    max_imu_frequency_hz: 200.0

    crop_box.min_x: [0.0]
    crop_box.min_y: [0.0]
    crop_box.min_z: [0.0]
    crop_box.max_x: [0.0]
    crop_box.max_y: [0.0]
    crop_box.max_z: [0.0]
